---
- name: Setup Linux machine
  hosts: local
  vars:
    current_user: "{{ ansible_user_id }}"
    go_version: "1.23.0"
  roles:
    - go
  tasks:
    - name: Ensure required packages are installed
      become: true
      ansible.builtin.apt:
        pkg:
          - git
          - ufw
          - curl
          - wget
          - zsh
          - ripgrep
          - unzip
          - bat
          - fzf
          - tree
          - zoxide
        state: present
        update_cache: true

    - name: Install Oh My Zsh # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1

    - name: Install zsh-syntax-highlighting plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1

    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ current_user }}"
        shell: /bin/zsh

    - name: Install Neovim
      become: true
      block:
        - name: Download Neovim
          ansible.builtin.get_url:
            url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
            dest: /tmp/nvim-linux-x86_64.tar.gz
            mode: "0644"
        - name: Remove existing Neovim installation
          ansible.builtin.file:
            path: "/opt/nvim-x86_64"
            state: absent
        - name: Extract Neovim
          ansible.builtin.unarchive:
            src: /tmp/nvim-linux-x86_64.tar.gz
            dest: /opt
            remote_src: true
            creates: /opt/nvim-linux-x86_64
        - name: Create symlink to neovim binary
          ansible.builtin.file:
            src: /opt/nvim-linux-x86_64/bin/nvim
            dest: /usr/local/bin/nvim
            state: link
